[project]
authors = ["Simone Massaro <simone.massaro@mone27.net>"]
channels = ["conda-forge"]
name = "TreeAI4Species"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
fiftyone = ">=1.3.2,<2"
ipykernel = ">=6.29.5,<7"
ipywidgets = ">=8.1.5,<9"
pandas = ">=2.2.3,<3"
python-dotenv = ">=1.0.1,<2"
openpyxl = ">=3.1.5,<4"
